#!/usr/bin/env bash
set -eo pipefail

image='local/rakudo-star-alpine:myproj'

if ! docker image inspect -f '{{.Id}}' $image &>/dev/null ; then
(
    cd $(mktemp -d)
    docker build -t $image -f - . <<'END_DOCKERFILE'
    FROM rakudo-star:alpine
    RUN zef install Data::Dump
END_DOCKERFILE
)
fi

docker run -i --rm --volume $PWD:/data --workdir /data $image rakudo - "$@" <<'END_SCRIPT'
#!/usr/bin/rakudo

use v6;
use Data::Dump;

my $name = 'hombre';
my %ht = (
    one => 1,
    two => 2,
    three => {
        bee => <hornet bumblebee>
    },
    four => [1..4]
);

say "This is $name";
say Dump(%ht);
END_SCRIPT
